CREATE DATABASE aula;
USE aula;

CREATE TABLE veiculos (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
marca VARCHAR(60) NOT NULL, 
modelo VARCHAR(60) NOT NULL,
ano INT NOT NULL,
proprietario VARCHAR(60) NOT NULL,
cor VARCHAR(20) NOT NULL
);

SELECT * FROM veiculos
